Sprint 2
Zaha250/middle.messenger.praktikum.yandex pull request #3
Opened 2022-06-18 10:43 UTC by Zaha250

2022-06-19 08:47 UTC, podlovchenko requested changes
Привет, лучше создать страницу со списком всех ссылок на странице для этого задания, добавить валидацию на странице входа и вывод данных в консоль
Есть ошибки typescript, попробуй выполнить команду `tsc`

2022-06-19 08:47 UTC, podlovchenko commented on src/index.ts
> +    // renderDOM('#app', new ServerErrorPage());
Почему закомментировано?

2022-06-19 08:47 UTC, podlovchenko commented on src/core/Router.ts
> +    static routes: { [key : string]: any } = {
Record<string, any>

2022-06-19 08:47 UTC, podlovchenko commented on src/pages/reg.ts
> +            onClick: () => new Router().push('/auth'),
Для роутер лучше использовать паттерн синглтон, а не каждый раз его заново создавать

2022-06-19 08:47 UTC, podlovchenko commented on src/pages/auth.ts
> +            onFocus: () => console.log('focus'),
Почему нет валидации?

2022-06-19 11:20 UTC, Zaha250 commented on src/index.ts
> +    // renderDOM('#app', new ServerErrorPage());
Потому что роутера как такого нет еще в этом спринте, это сделано, чтобы быстрее переходить по нужным страницам, как будет написан роутер, соответственно этого не будет

2022-06-20 12:29 UTC, podlovchenko approved these changes
Работу принимаю)

2022-06-20 12:40 UTC, merged